export interface QuizQuestion {
  quiz_id: string;
  question: string;
  options: string[];
  correct_option_index: number;
}

export interface Post {
  post_id: string;
  admin_name: string;
  content_text: string;
  screenshot_url: string;
  likes_count: number;
  shares_count: number;
  comments: { username: string; comment_text: string; timestamp: string }[];
  createdAt: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    quiz_id: '1',
    question: 'What is 1 + 1?',
    options: ['2', '4', '1', '5'],
    correct_option_index: 0,
  },
  {
    quiz_id: '2',
    question: 'What is 2 + 2?',
    options: ['4', '5', '3', '1'],
    correct_option_index: 0,
  },
  {
    quiz_id: '3',
    question: 'What is 3 + 3?',
    options: ['7', '9', '4', '6'],
    correct_option_index: 3,
  },
  {
    quiz_id: '4',
    question: 'What is 4 + 4?',
    options: ['11', '7', '5', '8'],
    correct_option_index: 3,
  },
  {
    quiz_id: '5',
    question: 'What is 5 + 5?',
    options: ['10', '8', '9', '13'],
    correct_option_index: 0,
  },
  {
    quiz_id: '6',
    question: 'What is 2 + 3?',
    options: ['5', '8', '4', '2'],
    correct_option_index: 0,
  },
  {
    quiz_id: '7',
    question: 'What is 3 + 4?',
    options: ['5', '10', '8', '7'],
    correct_option_index: 3,
  },
  {
    quiz_id: '8',
    question: 'What is 4 + 5?',
    options: ['6', '12', '8', '9'],
    correct_option_index: 3,
  },
  {
    quiz_id: '9',
    question: 'What is 1 + 2?',
    options: ['1', '6', '4', '3'],
    correct_option_index: 3,
  },
  {
    quiz_id: '10',
    question: 'What is 6 + 2?',
    options: ['8', '10', '5', '11'],
    correct_option_index: 0,
  },
  {
    quiz_id: '11',
    question: 'What is 7 + 1?',
    options: ['8', '10', '7', '11'],
    correct_option_index: 0,
  },
  {
    quiz_id: '12',
    question: 'What is 8 + 2?',
    options: ['11', '10', '13', '7'],
    correct_option_index: 1,
  },
  {
    quiz_id: '13',
    question: 'What is 9 + 1?',
    options: ['7', '8', '10', '11'],
    correct_option_index: 2,
  },
  {
    quiz_id: '14',
    question: 'What is 5 + 4?',
    options: ['10', '6', '9', '8'],
    correct_option_index: 2,
  },
  {
    quiz_id: '15',
    question: 'What is 6 + 3?',
    options: ['7', '6', '12', '9'],
    correct_option_index: 3,
  },
  {
    quiz_id: '16',
    question: 'What is 7 + 2?',
    options: ['8', '11', '7', '9'],
    correct_option_index: 3,
  },
  {
    quiz_id: '17',
    question: 'What is 3 + 6?',
    options: ['9', '12', '8', '6'],
    correct_option_index: 0,
  },
  {
    quiz_id: '18',
    question: 'What is 4 + 6?',
    options: ['8', '7', '10', '11'],
    correct_option_index: 2,
  },
  {
    quiz_id: '19',
    question: 'What is 2 + 7?',
    options: ['10', '9', '7', '6'],
    correct_option_index: 1,
  },
  {
    quiz_id: '20',
    question: 'What is 1 + 8?',
    options: ['9', '6', '7', '8'],
    correct_option_index: 0,
  },
  {
    quiz_id: '21',
    question: 'What is 10 + 5?',
    options: ['18', '15', '12', '14'],
    correct_option_index: 1,
  },
  {
    quiz_id: '22',
    question: 'What is 10 + 10?',
    options: ['18', '23', '21', '20'],
    correct_option_index: 3,
  },
  {
    quiz_id: '23',
    question: 'What is 9 + 9?',
    options: ['21', '15', '19', '18'],
    correct_option_index: 3,
  },
  {
    quiz_id: '24',
    question: 'What is 8 + 8?',
    options: ['18', '17', '13', '16'],
    correct_option_index: 3,
  },
  {
    quiz_id: '25',
    question: 'What is 7 + 7?',
    options: ['11', '14', '15', '13'],
    correct_option_index: 1,
  },
  {
    quiz_id: '26',
    question: 'What is 6 + 6?',
    options: ['12', '11', '9', '13'],
    correct_option_index: 0,
  },
  {
    quiz_id: '27',
    question: 'What is 15 + 5?',
    options: ['18', '20', '23', '17'],
    correct_option_index: 1,
  },
  {
    quiz_id: '28',
    question: 'What is 20 + 10?',
    options: ['28', '30', '27', '29'],
    correct_option_index: 1,
  },
  {
    quiz_id: '29',
    question: 'What is 12 + 8?',
    options: ['21', '19', '17', '20'],
    correct_option_index: 3,
  },
  {
    quiz_id: '30',
    question: 'What is 11 + 9?',
    options: ['17', '21', '18', '20'],
    correct_option_index: 3,
  },
  {
    quiz_id: '31',
    question: 'What is 5 - 2?',
    options: ['4', '2', '0', '3'],
    correct_option_index: 3,
  },
  {
    quiz_id: '32',
    question: 'What is 10 - 4?',
    options: ['6', '3', '9', '8'],
    correct_option_index: 0,
  },
  {
    quiz_id: '33',
    question: 'What is 8 - 3?',
    options: ['3', '2', '8', '5'],
    correct_option_index: 3,
  },
  {
    quiz_id: '34',
    question: 'What is 9 - 5?',
    options: ['7', '6', '2', '4'],
    correct_option_index: 3,
  },
  {
    quiz_id: '35',
    question: 'What is 6 - 1?',
    options: ['6', '2', '7', '5'],
    correct_option_index: 3,
  },
  {
    quiz_id: '36',
    question: 'What is 7 - 3?',
    options: ['4', '3', '1', '6'],
    correct_option_index: 0,
  },
  {
    quiz_id: '37',
    question: 'What is 12 - 5?',
    options: ['8', '9', '7', '6'],
    correct_option_index: 2,
  },
  {
    quiz_id: '38',
    question: 'What is 15 - 7?',
    options: ['6', '9', '5', '8'],
    correct_option_index: 3,
  },
  {
    quiz_id: '39',
    question: 'What is 20 - 10?',
    options: ['10', '13', '11', '12'],
    correct_option_index: 0,
  },
  {
    quiz_id: '40',
    question: 'What is 10 - 1?',
    options: ['12', '9', '10', '11'],
    correct_option_index: 1,
  },
  {
    quiz_id: '41',
    question: 'What is 9 - 2?',
    options: ['9', '7', '10', '6'],
    correct_option_index: 1,
  },
  {
    quiz_id: '42',
    question: 'What is 8 - 4?',
    options: ['1', '2', '5', '4'],
    correct_option_index: 3,
  },
  {
    quiz_id: '43',
    question: 'What is 7 - 4?',
    options: ['3', '0', '4', '2'],
    correct_option_index: 0,
  },
  {
    quiz_id: '44',
    question: 'What is 6 - 2?',
    options: ['6', '2', '4', '1'],
    correct_option_index: 2,
  },
  {
    quiz_id: '45',
    question: 'What is 10 - 6?',
    options: ['4', '7', '6', '3'],
    correct_option_index: 0,
  },
  {
    quiz_id: '46',
    question: 'What is 10 - 7?',
    options: ['3', '4', '0', '2'],
    correct_option_index: 0,
  },
  {
    quiz_id: '47',
    question: 'What is 10 - 8?',
    options: ['2', '0', '4', '5'],
    correct_option_index: 0,
  },
  {
    quiz_id: '48',
    question: 'What is 10 - 9?',
    options: ['3', '1', '0', '4'],
    correct_option_index: 1,
  },
  {
    quiz_id: '49',
    question: 'What is 5 - 1?',
    options: ['6', '2', '4', '7'],
    correct_option_index: 2,
  },
  {
    quiz_id: '50',
    question: 'What is 4 - 1?',
    options: ['4', '6', '2', '3'],
    correct_option_index: 3,
  },
  {
    quiz_id: '51',
    question: 'What is 20 - 5?',
    options: ['14', '12', '13', '15'],
    correct_option_index: 3,
  },
  {
    quiz_id: '52',
    question: 'What is 15 - 5?',
    options: ['9', '8', '7', '10'],
    correct_option_index: 3,
  },
  {
    quiz_id: '53',
    question: 'What is 18 - 9?',
    options: ['6', '9', '8', '12'],
    correct_option_index: 1,
  },
  {
    quiz_id: '54',
    question: 'What is 16 - 8?',
    options: ['7', '11', '8', '10'],
    correct_option_index: 2,
  },
  {
    quiz_id: '55',
    question: 'What is 14 - 7?',
    options: ['7', '8', '9', '6'],
    correct_option_index: 0,
  },
  {
    quiz_id: '56',
    question: 'What is 2 × 2?',
    options: ['6', '5', '3', '4'],
    correct_option_index: 3,
  },
  {
    quiz_id: '57',
    question: 'What is 2 × 3?',
    options: ['2', '6', '5', '4'],
    correct_option_index: 1,
  },
  {
    quiz_id: '58',
    question: 'What is 2 × 4?',
    options: ['12', '11', '8', '5'],
    correct_option_index: 2,
  },
  {
    quiz_id: '59',
    question: 'What is 2 × 5?',
    options: ['10', '8', '6', '9'],
    correct_option_index: 0,
  },
  {
    quiz_id: '60',
    question: 'What is 3 × 3?',
    options: ['9', '13', '11', '8'],
    correct_option_index: 0,
  },
  {
    quiz_id: '61',
    question: 'What is 3 × 4?',
    options: ['12', '14', '13', '15'],
    correct_option_index: 0,
  },
  {
    quiz_id: '62',
    question: 'What is 2 × 6?',
    options: ['12', '10', '11', '13'],
    correct_option_index: 0,
  },
  {
    quiz_id: '63',
    question: 'What is 2 × 7?',
    options: ['14', '13', '17', '15'],
    correct_option_index: 0,
  },
  {
    quiz_id: '64',
    question: 'What is 2 × 8?',
    options: ['16', '15', '18', '20'],
    correct_option_index: 0,
  },
  {
    quiz_id: '65',
    question: 'What is 2 × 9?',
    options: ['17', '14', '21', '18'],
    correct_option_index: 3,
  },
  {
    quiz_id: '66',
    question: 'What is 3 × 5?',
    options: ['11', '19', '16', '15'],
    correct_option_index: 3,
  },
  {
    quiz_id: '67',
    question: 'What is 4 × 4?',
    options: ['18', '20', '13', '16'],
    correct_option_index: 3,
  },
  {
    quiz_id: '68',
    question: 'What is 2 × 10?',
    options: ['20', '23', '22', '16'],
    correct_option_index: 0,
  },
  {
    quiz_id: '69',
    question: 'What is 5 × 5?',
    options: ['26', '25', '27', '28'],
    correct_option_index: 1,
  },
  {
    quiz_id: '70',
    question: 'What is 3 × 6?',
    options: ['17', '19', '14', '18'],
    correct_option_index: 3,
  },
  {
    quiz_id: '71',
    question: 'What is 4 × 5?',
    options: ['22', '21', '24', '20'],
    correct_option_index: 3,
  },
  {
    quiz_id: '72',
    question: 'What is 1 × 9?',
    options: ['9', '10', '13', '11'],
    correct_option_index: 0,
  },
  {
    quiz_id: '73',
    question: 'What is 1 × 10?',
    options: ['9', '10', '14', '7'],
    correct_option_index: 1,
  },
  {
    quiz_id: '74',
    question: 'What is 6 × 2?',
    options: ['12', '8', '14', '9'],
    correct_option_index: 0,
  },
  {
    quiz_id: '75',
    question: 'What is 7 × 2?',
    options: ['14', '13', '16', '11'],
    correct_option_index: 0,
  },
  {
    quiz_id: '76',
    question: 'What color is the sky on a clear day?',
    options: ['Green', 'Blue', 'Red', 'Yellow'],
    correct_option_index: 1,
  },
  {
    quiz_id: '77',
    question: 'What color is grass?',
    options: ['Blue', 'Green', 'Red', 'Black'],
    correct_option_index: 1,
  },
  {
    quiz_id: '78',
    question: 'How many days are in a week?',
    options: ['5', '6', '7', '8'],
    correct_option_index: 2,
  },
  {
    quiz_id: '79',
    question: 'How many months are in a year?',
    options: ['10', '11', '12', '13'],
    correct_option_index: 2,
  },
  {
    quiz_id: '80',
    question: 'What is the color of a banana?',
    options: ['Purple', 'Yellow', 'Blue', 'Black'],
    correct_option_index: 1,
  },
  {
    quiz_id: '81',
    question: 'How many legs does a dog have?',
    options: ['2', '3', '4', '5'],
    correct_option_index: 2,
  },
  {
    quiz_id: '82',
    question: 'What do bees make?',
    options: ['Milk', 'Honey', 'Butter', 'Juice'],
    correct_option_index: 1,
  },
  {
    quiz_id: '83',
    question: 'What do cows give us?',
    options: ['Milk', 'Oil', 'Water', 'Bread'],
    correct_option_index: 0,
  },
  {
    quiz_id: '84',
    question: 'What is the opposite of hot?',
    options: ['Cold', 'Big', 'Fast', 'Loud'],
    correct_option_index: 0,
  },
  {
    quiz_id: '85',
    question: 'What is the opposite of big?',
    options: ['Tall', 'Small', 'Wide', 'Long'],
    correct_option_index: 1,
  },
  {
    quiz_id: '86',
    question: 'What is the opposite of up?',
    options: ['Down', 'Left', 'Right', 'Over'],
    correct_option_index: 0,
  },
  {
    quiz_id: '87',
    question: 'What is the opposite of day?',
    options: ['Night', 'Sun', 'Sky', 'Light'],
    correct_option_index: 0,
  },
  {
    quiz_id: '88',
    question: 'What is the opposite of happy?',
    options: ['Sad', 'Fun', 'Nice', 'Kind'],
    correct_option_index: 0,
  },
  {
    quiz_id: '89',
    question: 'What is the opposite of fast?',
    options: ['Slow', 'Quick', 'Loud', 'Small'],
    correct_option_index: 0,
  },
  {
    quiz_id: '90',
    question: 'What is the opposite of open?',
    options: ['Closed', 'Wide', 'Empty', 'Full'],
    correct_option_index: 0,
  },
  {
    quiz_id: '91',
    question: 'Which animal says \'moo\'?',
    options: ['Dog', 'Cat', 'Cow', 'Duck'],
    correct_option_index: 2,
  },
  {
    quiz_id: '92',
    question: 'Which animal says \'woof\'?',
    options: ['Cat', 'Dog', 'Bird', 'Fish'],
    correct_option_index: 1,
  },
  {
    quiz_id: '93',
    question: 'Which animal says \'meow\'?',
    options: ['Dog', 'Cow', 'Cat', 'Duck'],
    correct_option_index: 2,
  },
  {
    quiz_id: '94',
    question: 'What do fish live in?',
    options: ['Trees', 'Water', 'Sand', 'Grass'],
    correct_option_index: 1,
  },
  {
    quiz_id: '95',
    question: 'What do birds do in the sky?',
    options: ['Swim', 'Fly', 'Run', 'Crawl'],
    correct_option_index: 1,
  },
  {
    quiz_id: '96',
    question: 'What season comes after winter?',
    options: ['Summer', 'Spring', 'Fall', 'Rain'],
    correct_option_index: 1,
  },
  {
    quiz_id: '97',
    question: 'What season is the hottest?',
    options: ['Winter', 'Summer', 'Spring', 'Fall'],
    correct_option_index: 1,
  },
  {
    quiz_id: '98',
    question: 'What season is the coldest?',
    options: ['Summer', 'Winter', 'Spring', 'Fall'],
    correct_option_index: 1,
  },
  {
    quiz_id: '99',
    question: 'How many colors are in a rainbow?',
    options: ['5', '6', '7', '8'],
    correct_option_index: 2,
  },
  {
    quiz_id: '100',
    question: 'What shape has 3 sides?',
    options: ['Square', 'Circle', 'Triangle', 'Rectangle'],
    correct_option_index: 2,
  },
  {
    quiz_id: '101',
    question: 'What shape has 4 equal sides?',
    options: ['Circle', 'Square', 'Triangle', 'Oval'],
    correct_option_index: 1,
  },
  {
    quiz_id: '102',
    question: 'What shape is a ball?',
    options: ['Square', 'Circle', 'Triangle', 'Star'],
    correct_option_index: 1,
  },
  {
    quiz_id: '103',
    question: 'What do you use to write?',
    options: ['Spoon', 'Pen', 'Plate', 'Shoe'],
    correct_option_index: 1,
  },
  {
    quiz_id: '104',
    question: 'What do you use to cut paper?',
    options: ['Scissors', 'Fork', 'Spoon', 'Comb'],
    correct_option_index: 0,
  },
  {
    quiz_id: '105',
    question: 'What do you wear on your feet?',
    options: ['Hat', 'Gloves', 'Shoes', 'Scarf'],
    correct_option_index: 2,
  },
  {
    quiz_id: '106',
    question: 'What do you wear on your head?',
    options: ['Shoes', 'Hat', 'Socks', 'Belt'],
    correct_option_index: 1,
  },
  {
    quiz_id: '107',
    question: 'What do you use to see?',
    options: ['Ears', 'Nose', 'Eyes', 'Mouth'],
    correct_option_index: 2,
  },
  {
    quiz_id: '108',
    question: 'What do you use to hear?',
    options: ['Eyes', 'Ears', 'Nose', 'Hands'],
    correct_option_index: 1,
  },
  {
    quiz_id: '109',
    question: 'What do you use to smell?',
    options: ['Nose', 'Eyes', 'Ears', 'Feet'],
    correct_option_index: 0,
  },
  {
    quiz_id: '110',
    question: 'What is the first meal of the day called?',
    options: ['Lunch', 'Dinner', 'Breakfast', 'Snack'],
    correct_option_index: 2,
  },
  {
    quiz_id: '111',
    question: 'What do you sleep on?',
    options: ['Chair', 'Bed', 'Table', 'Floor'],
    correct_option_index: 1,
  },
  {
    quiz_id: '112',
    question: 'What do you drink when thirsty?',
    options: ['Water', 'Sand', 'Rocks', 'Paper'],
    correct_option_index: 0,
  },
  {
    quiz_id: '113',
    question: 'What fruit is red and round, often eaten as pie?',
    options: ['Apple', 'Banana', 'Grape', 'Lemon'],
    correct_option_index: 0,
  },
  {
    quiz_id: '114',
    question: 'What color is the sun?',
    options: ['Blue', 'Yellow', 'Green', 'Purple'],
    correct_option_index: 1,
  },
  {
    quiz_id: '115',
    question: 'What color is snow?',
    options: ['Black', 'White', 'Red', 'Green'],
    correct_option_index: 1,
  },
  {
    quiz_id: '116',
    question: 'What is the color of blood?',
    options: ['Blue', 'Red', 'Green', 'Yellow'],
    correct_option_index: 1,
  },
  {
    quiz_id: '117',
    question: 'How many eyes does a person have?',
    options: ['1', '2', '3', '4'],
    correct_option_index: 1,
  },
  {
    quiz_id: '118',
    question: 'How many fingers are on one hand?',
    options: ['4', '5', '6', '10'],
    correct_option_index: 1,
  },
  {
    quiz_id: '119',
    question: 'How many hands does a person have?',
    options: ['1', '2', '3', '4'],
    correct_option_index: 1,
  },
  {
    quiz_id: '120',
    question: 'What do you use an umbrella for?',
    options: ['Sun', 'Rain', 'Snow', 'Wind'],
    correct_option_index: 1,
  },
  {
    quiz_id: '121',
    question: 'What animal is known as man\'s best friend?',
    options: ['Cat', 'Dog', 'Bird', 'Fish'],
    correct_option_index: 1,
  },
  {
    quiz_id: '122',
    question: 'What do plants need to grow?',
    options: ['Water and sunlight', 'Rocks', 'Metal', 'Sand'],
    correct_option_index: 0,
  },
  {
    quiz_id: '123',
    question: 'What is frozen water called?',
    options: ['Steam', 'Ice', 'Rain', 'Fog'],
    correct_option_index: 1,
  },
  {
    quiz_id: '124',
    question: 'What is water that falls from the sky called?',
    options: ['Snow', 'Rain', 'Wind', 'Cloud'],
    correct_option_index: 1,
  },
  {
    quiz_id: '125',
    question: 'What do you call a baby dog?',
    options: ['Kitten', 'Puppy', 'Cub', 'Chick'],
    correct_option_index: 1,
  },
  {
    quiz_id: '126',
    question: 'What do you call a baby cat?',
    options: ['Puppy', 'Kitten', 'Calf', 'Foal'],
    correct_option_index: 1,
  },
  {
    quiz_id: '127',
    question: 'What do you call a baby cow?',
    options: ['Calf', 'Cub', 'Kid', 'Foal'],
    correct_option_index: 0,
  },
  {
    quiz_id: '128',
    question: 'Which is bigger, an elephant or a mouse?',
    options: ['Elephant', 'Mouse', 'Same size', 'Neither'],
    correct_option_index: 0,
  },
  {
    quiz_id: '129',
    question: 'Which is smaller, an ant or a lion?',
    options: ['Lion', 'Ant', 'Same size', 'Neither'],
    correct_option_index: 1,
  },
  {
    quiz_id: '130',
    question: 'What do you use to talk on far away?',
    options: ['Phone', 'Spoon', 'Book', 'Chair'],
    correct_option_index: 0,
  },
  {
    quiz_id: '131',
    question: 'What do we use to tell time?',
    options: ['Clock', 'Plate', 'Shoe', 'Cup'],
    correct_option_index: 0,
  },
  {
    quiz_id: '132',
    question: 'How many letters are in the English alphabet?',
    options: ['24', '25', '26', '27'],
    correct_option_index: 2,
  },
  {
    quiz_id: '133',
    question: 'What comes after Monday?',
    options: ['Sunday', 'Tuesday', 'Wednesday', 'Friday'],
    correct_option_index: 1,
  },
  {
    quiz_id: '134',
    question: 'What comes after Sunday?',
    options: ['Monday', 'Saturday', 'Tuesday', 'Friday'],
    correct_option_index: 0,
  },
  {
    quiz_id: '135',
    question: 'What is the last day of the week (common order)?',
    options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    correct_option_index: 2,
  },
  {
    quiz_id: '136',
    question: 'What color do you get by mixing blue and yellow?',
    options: ['Green', 'Purple', 'Orange', 'Red'],
    correct_option_index: 0,
  },
  {
    quiz_id: '137',
    question: 'What color do you get by mixing red and white?',
    options: ['Pink', 'Brown', 'Black', 'Blue'],
    correct_option_index: 0,
  },
  {
    quiz_id: '138',
    question: 'What color do you get by mixing red and yellow?',
    options: ['Orange', 'Green', 'Purple', 'Blue'],
    correct_option_index: 0,
  },
  {
    quiz_id: '139',
    question: 'What do you call the star closest to Earth?',
    options: ['Moon', 'Sun', 'Mars', 'Venus'],
    correct_option_index: 1,
  },
  {
    quiz_id: '140',
    question: 'What do we call the natural satellite of Earth?',
    options: ['Sun', 'Moon', 'Star', 'Mars'],
    correct_option_index: 1,
  },
  {
    quiz_id: '141',
    question: 'What is H2O commonly known as?',
    options: ['Water', 'Air', 'Salt', 'Sugar'],
    correct_option_index: 0,
  },
  {
    quiz_id: '142',
    question: 'Which animal is known as the king of the jungle?',
    options: ['Tiger', 'Lion', 'Elephant', 'Bear'],
    correct_option_index: 1,
  },
  {
    quiz_id: '143',
    question: 'Which animal has a long neck?',
    options: ['Giraffe', 'Pig', 'Cat', 'Dog'],
    correct_option_index: 0,
  },
  {
    quiz_id: '144',
    question: 'Which animal has a trunk?',
    options: ['Elephant', 'Horse', 'Dog', 'Cat'],
    correct_option_index: 0,
  },
  {
    quiz_id: '145',
    question: 'Which insect makes honey?',
    options: ['Ant', 'Bee', 'Fly', 'Spider'],
    correct_option_index: 1,
  },
  {
    quiz_id: '146',
    question: 'How many wheels does a bicycle have?',
    options: ['1', '2', '3', '4'],
    correct_option_index: 1,
  },
  {
    quiz_id: '147',
    question: 'How many wheels does a car usually have?',
    options: ['2', '3', '4', '6'],
    correct_option_index: 2,
  },
  {
    quiz_id: '148',
    question: 'What do you use to brush your teeth?',
    options: ['Comb', 'Toothbrush', 'Spoon', 'Pen'],
    correct_option_index: 1,
  },
  {
    quiz_id: '149',
    question: 'What do you use to comb your hair?',
    options: ['Comb', 'Fork', 'Spoon', 'Pen'],
    correct_option_index: 0,
  },
  {
    quiz_id: '150',
    question: 'What is the capital of your own country called in general terms?',
    options: ['City', 'Capital', 'Town', 'Village'],
    correct_option_index: 1,
  },
  {
    quiz_id: '151',
    question: 'Which is a fruit: Apple or Carrot?',
    options: ['Apple', 'Carrot', 'Potato', 'Onion'],
    correct_option_index: 0,
  },
  {
    quiz_id: '152',
    question: 'Which is a vegetable: Banana or Potato?',
    options: ['Banana', 'Potato', 'Mango', 'Grape'],
    correct_option_index: 1,
  },
  {
    quiz_id: '153',
    question: 'What do you call a place where you buy food?',
    options: ['School', 'Market', 'Hospital', 'Park'],
    correct_option_index: 1,
  },
  {
    quiz_id: '154',
    question: 'What do you call a place where you learn?',
    options: ['Market', 'School', 'Zoo', 'Bank'],
    correct_option_index: 1,
  },
  {
    quiz_id: '155',
    question: 'What do you call a place with wild animals to see?',
    options: ['Zoo', 'Bank', 'School', 'Market'],
    correct_option_index: 0,
  },
  {
    quiz_id: '156',
    question: 'What do you call a doctor for animals?',
    options: ['Vet', 'Dentist', 'Teacher', 'Chef'],
    correct_option_index: 0,
  },
  {
    quiz_id: '157',
    question: 'What do you call a person who teaches?',
    options: ['Doctor', 'Teacher', 'Driver', 'Cook'],
    correct_option_index: 1,
  },
  {
    quiz_id: '158',
    question: 'What do you call a person who cooks food?',
    options: ['Chef', 'Pilot', 'Nurse', 'Farmer'],
    correct_option_index: 0,
  },
  {
    quiz_id: '159',
    question: 'What do you call a person who flies planes?',
    options: ['Pilot', 'Driver', 'Chef', 'Teacher'],
    correct_option_index: 0,
  },
  {
    quiz_id: '160',
    question: 'What is the opposite of empty?',
    options: ['Full', 'Small', 'Short', 'Light'],
    correct_option_index: 0,
  },
  {
    quiz_id: '161',
    question: 'What is the opposite of wet?',
    options: ['Dry', 'Cold', 'Soft', 'Hard'],
    correct_option_index: 0,
  },
  {
    quiz_id: '162',
    question: 'What is the opposite of light (weight)?',
    options: ['Heavy', 'Bright', 'Dark', 'Fast'],
    correct_option_index: 0,
  },
  {
    quiz_id: '163',
    question: 'What is the opposite of clean?',
    options: ['Dirty', 'New', 'Old', 'Big'],
    correct_option_index: 0,
  },
  {
    quiz_id: '164',
    question: 'What is the opposite of new?',
    options: ['Old', 'Small', 'Fast', 'High'],
    correct_option_index: 0,
  },
  {
    quiz_id: '165',
    question: 'What is the opposite of soft?',
    options: ['Hard', 'Warm', 'Sweet', 'Fast'],
    correct_option_index: 0,
  },
  {
    quiz_id: '166',
    question: 'What number comes after 9?',
    options: ['8', '10', '11', '7'],
    correct_option_index: 1,
  },
  {
    quiz_id: '167',
    question: 'What number comes before 5?',
    options: ['3', '4', '6', '7'],
    correct_option_index: 1,
  },
  {
    quiz_id: '168',
    question: 'Which number is bigger, 10 or 5?',
    options: ['10', '5', 'Equal', 'Neither'],
    correct_option_index: 0,
  },
  {
    quiz_id: '169',
    question: 'Which number is smaller, 3 or 8?',
    options: ['8', '3', 'Equal', 'Neither'],
    correct_option_index: 1,
  },
  {
    quiz_id: '170',
    question: 'How many minutes are in an hour?',
    options: ['30', '45', '60', '90'],
    correct_option_index: 2,
  },
  {
    quiz_id: '171',
    question: 'How many hours are in a day?',
    options: ['12', '24', '20', '30'],
    correct_option_index: 1,
  },
  {
    quiz_id: '172',
    question: 'How many seconds are in a minute?',
    options: ['30', '60', '100', '50'],
    correct_option_index: 1,
  },
  {
    quiz_id: '173',
    question: 'What do you call frozen rain?',
    options: ['Hail', 'Fog', 'Wind', 'Mist'],
    correct_option_index: 0,
  },
  {
    quiz_id: '174',
    question: 'What gas do we breathe in to live?',
    options: ['Oxygen', 'Carbon', 'Helium', 'Nitrogen'],
    correct_option_index: 0,
  },
  {
    quiz_id: '175',
    question: 'What is the color of the ocean usually shown as?',
    options: ['Blue', 'Red', 'Green', 'Yellow'],
    correct_option_index: 0,
  },
  {
    quiz_id: '176',
    question: 'What do you call the place you live in with your family?',
    options: ['Home', 'School', 'Park', 'Market'],
    correct_option_index: 0,
  },
  {
    quiz_id: '177',
    question: 'What do we call the person who delivers mail?',
    options: ['Postman', 'Fisherman', 'Farmer', 'Driver'],
    correct_option_index: 0,
  },
  {
    quiz_id: '178',
    question: 'What do we use to unlock a door?',
    options: ['Key', 'Spoon', 'Book', 'Cup'],
    correct_option_index: 0,
  },
  {
    quiz_id: '179',
    question: 'What is used to write on a blackboard?',
    options: ['Chalk', 'Pen', 'Fork', 'Spoon'],
    correct_option_index: 0,
  },
  {
    quiz_id: '180',
    question: 'Which is a mode of transport: Bus or Table?',
    options: ['Bus', 'Table', 'Chair', 'Bed'],
    correct_option_index: 0,
  },
  {
    quiz_id: '181',
    question: 'Which is a mode of transport: Train or Pen?',
    options: ['Train', 'Pen', 'Book', 'Cup'],
    correct_option_index: 0,
  },
  {
    quiz_id: '182',
    question: 'What do you call water that is frozen solid?',
    options: ['Ice', 'Steam', 'Rain', 'Fog'],
    correct_option_index: 0,
  },
  {
    quiz_id: '183',
    question: 'Which animal lays eggs and can fly?',
    options: ['Bird', 'Dog', 'Cat', 'Cow'],
    correct_option_index: 0,
  },
  {
    quiz_id: '184',
    question: 'What is the color of coal?',
    options: ['White', 'Black', 'Red', 'Green'],
    correct_option_index: 1,
  },
  {
    quiz_id: '185',
    question: 'What do you call the meal eaten at night?',
    options: ['Breakfast', 'Lunch', 'Dinner', 'Snack'],
    correct_option_index: 2,
  },
  {
    quiz_id: '186',
    question: 'What is 2 plus 0?',
    options: ['1', '2', '3', '0'],
    correct_option_index: 1,
  },
  {
    quiz_id: '187',
    question: 'What number is half of 10?',
    options: ['4', '5', '6', '3'],
    correct_option_index: 1,
  },
  {
    quiz_id: '188',
    question: 'What number is half of 20?',
    options: ['8', '10', '12', '15'],
    correct_option_index: 1,
  },
  {
    quiz_id: '189',
    question: 'How many zeros are in the number 100?',
    options: ['1', '2', '3', '0'],
    correct_option_index: 1,
  },
  {
    quiz_id: '190',
    question: 'What is the shape of a football (soccer ball)?',
    options: ['Square', 'Circle', 'Triangle', 'Rectangle'],
    correct_option_index: 1,
  },
  {
    quiz_id: '191',
    question: 'What is the color of an apple usually?',
    options: ['Red', 'Blue', 'Black', 'Purple'],
    correct_option_index: 0,
  },
  {
    quiz_id: '192',
    question: 'What do you call the tool used to hammer nails?',
    options: ['Hammer', 'Spoon', 'Fork', 'Pen'],
    correct_option_index: 0,
  },
  {
    quiz_id: '193',
    question: 'What do you use to measure temperature?',
    options: ['Thermometer', 'Ruler', 'Clock', 'Scale'],
    correct_option_index: 0,
  },
  {
    quiz_id: '194',
    question: 'What do you use to measure length?',
    options: ['Ruler', 'Clock', 'Thermometer', 'Scale'],
    correct_option_index: 0,
  },
  {
    quiz_id: '195',
    question: 'What is the name of our planet?',
    options: ['Mars', 'Earth', 'Venus', 'Jupiter'],
    correct_option_index: 1,
  },
  {
    quiz_id: '196',
    question: 'How many continents are there on Earth?',
    options: ['5', '6', '7', '8'],
    correct_option_index: 2,
  },
  {
    quiz_id: '197',
    question: 'What do you call frozen dessert made from milk?',
    options: ['Ice cream', 'Bread', 'Cake', 'Soup'],
    correct_option_index: 0,
  },
  {
    quiz_id: '198',
    question: 'What is the main color of a stop sign?',
    options: ['Green', 'Red', 'Blue', 'Yellow'],
    correct_option_index: 1,
  },
  {
    quiz_id: '199',
    question: 'What color means \'go\' on a traffic light?',
    options: ['Red', 'Green', 'Yellow', 'Blue'],
    correct_option_index: 1,
  },
  {
    quiz_id: '200',
    question: 'What color means \'stop\' on a traffic light?',
    options: ['Green', 'Red', 'Yellow', 'Blue'],
    correct_option_index: 1,
  },
  {
    quiz_id: '201',
    question: 'What do we call a person who fixes teeth?',
    options: ['Dentist', 'Farmer', 'Pilot', 'Chef'],
    correct_option_index: 0,
  },
  {
    quiz_id: '202',
    question: 'What do we call a person who treats sick people?',
    options: ['Doctor', 'Teacher', 'Driver', 'Farmer'],
    correct_option_index: 0,
  },
  {
    quiz_id: '203',
    question: 'What is the opposite of left?',
    options: ['Right', 'Up', 'Down', 'Straight'],
    correct_option_index: 0,
  },
  {
    quiz_id: '204',
    question: 'What is the opposite of true?',
    options: ['False', 'Real', 'Correct', 'Right'],
    correct_option_index: 0,
  },
  {
    quiz_id: '205',
    question: 'What is the opposite of start?',
    options: ['Finish', 'Begin', 'Open', 'Play'],
    correct_option_index: 0,
  },
  {
    quiz_id: '206',
    question: 'What is the opposite of buy?',
    options: ['Sell', 'Give', 'Take', 'Keep'],
    correct_option_index: 0,
  },
  {
    quiz_id: '207',
    question: 'What is the opposite of win?',
    options: ['Lose', 'Play', 'Try', 'Run'],
    correct_option_index: 0,
  },
];

export const FEED_POSTS: Post[] = [
  {
    post_id: '1',
    admin_name: 'QuizBox Admin',
    content_text: 'Congratulations to all our top collectors this week! Keep playing, keep winning. New Gift Vouchers dropping every Friday.',
    screenshot_url: 'https://picsum.photos/seed/qb1/400/220',
    likes_count: 312,
    shares_count: 47,
    comments: [
      { username: 'Ali_K', comment_text: 'Great platform, love collecting tokens!', timestamp: new Date(Date.now() - 7200000).toISOString() },
      { username: 'Sara_M', comment_text: 'When is the next Mega Draw?', timestamp: new Date(Date.now() - 3600000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    post_id: '2',
    admin_name: 'Reward Hub',
    content_text: 'Today\'s top players have been rewarded! 25 Gift Vouchers successfully processed. Play the Brain Quiz daily and spin the wheel to boost your token collection.',
    screenshot_url: 'https://picsum.photos/seed/qb2/400/220',
    likes_count: 198,
    shares_count: 31,
    comments: [
      { username: 'ZainQ', comment_text: 'Got my voucher, very fast!', timestamp: new Date(Date.now() - 1800000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    post_id: '3',
    admin_name: 'QuizBox Admin',
    content_text: 'New Captcha Solver module is now live! Complete 5 captchas and collect 20 bonus tokens. Stay sharp and keep collecting.',
    screenshot_url: 'https://picsum.photos/seed/qb3/400/220',
    likes_count: 421,
    shares_count: 68,
    comments: [],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    post_id: '4',
    admin_name: 'Reward Hub',
    content_text: 'Rs. 500 and Rs. 1000 Gift Vouchers processed today! Redeem via EasyPaisa and JazzCash. Check the Claim Rewards section for details.',
    screenshot_url: 'https://picsum.photos/seed/qb4/400/220',
    likes_count: 567,
    shares_count: 94,
    comments: [
      { username: 'Hassan_B', comment_text: 'Love this reward system!', timestamp: new Date(Date.now() - 5400000).toISOString() },
      { username: 'Nadia_R', comment_text: 'Almost at 5000 tokens!', timestamp: new Date(Date.now() - 900000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    post_id: '5',
    admin_name: 'QuizBox Admin',
    content_text: 'Spin the Wheel daily for your FREE spins! Land on 100 tokens for a mega boost. Three free spins every day — watch a video for extra turns.',
    screenshot_url: 'https://picsum.photos/seed/qb5/400/220',
    likes_count: 289,
    shares_count: 42,
    comments: [],
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
];

export const BANNED_WORDS = ['scam', 'fake', 'fraud', 'bakwas', 'chor', 'cheat', 'loot', 'bekar', 'worst', 'pathetic'];

export const SPIN_SEGMENTS = [
  { label: '5', tokens: 5, color: '#F5C842', textColor: '#0A0A14' },
  { label: 'Skip', tokens: 0, color: '#2A1A5E', textColor: '#A090FF' },
  { label: '8', tokens: 8, color: '#1A3A28', textColor: '#2ED573' },
  { label: '20', tokens: 20, color: '#FF6B35', textColor: '#FFFFFF' },
  { label: '5', tokens: 5, color: '#F5C842', textColor: '#0A0A14' },
  { label: 'Skip', tokens: 0, color: '#2A1A5E', textColor: '#A090FF' },
  { label: '30', tokens: 30, color: '#FF4757', textColor: '#FFFFFF' },
  { label: '8', tokens: 8, color: '#1A3A28', textColor: '#2ED573' },
];
